# Generated by Django 5.1.2 on 2024-11-07 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_rooms', models.SmallIntegerField()),
                ('number_floor', models.SmallIntegerField()),
                ('square', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('code_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.infobuilding')),
            ],
        ),
    ]
