# Generated by Django 5.1.2 on 2024-11-07 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_apartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_apartment', models.CharField(max_length=200)),
                ('data_change', models.DateField(blank=True, null=True)),
                ('id_apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.apartment')),
            ],
        ),
    ]
