# Generated by Django 5.1.2 on 2024-11-07 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_regularcustomers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_deal', models.DateField(blank=True, null=True)),
                ('id_apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.apartment')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.regularcustomers')),
            ],
        ),
    ]
