# Generated by Django 5.1.2 on 2024-11-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0005_deal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(max_length=200)),
                ('number_phone', models.CharField(max_length=20)),
                ('status_application', models.CharField(max_length=200)),
            ],
        ),
    ]
