# Generated by Django 5.1.2 on 2024-11-08 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0007_alter_apartment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationwebsite',
            options={'verbose_name': 'Заявки с сайта', 'verbose_name_plural': 'Заявки с сайта'},
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'verbose_name': 'Сделка - продано', 'verbose_name_plural': 'Сделка - продано'},
        ),
        migrations.AlterModelOptions(
            name='infobuilding',
            options={'verbose_name': 'Информация о ЖК', 'verbose_name_plural': 'Информация о ЖК'},
        ),
        migrations.AlterModelOptions(
            name='regularcustomers',
            options={'verbose_name': 'Постоянные клиенты', 'verbose_name_plural': 'Постоянные клиенты'},
        ),
        migrations.AlterModelOptions(
            name='statusapartment',
            options={'verbose_name': 'Статус Апартаментов', 'verbose_name_plural': 'Статус Апартаментов'},
        ),
        migrations.AlterField(
            model_name='applicationwebsite',
            name='name_client',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='applicationwebsite',
            name='number_phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='applicationwebsite',
            name='status_application',
            field=models.CharField(max_length=200, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='data_deal',
            field=models.DateField(blank=True, null=True, verbose_name='Дата сделки'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='id_apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.apartment', verbose_name='ID Апартамента'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.regularcustomers', verbose_name='ID Клиента'),
        ),
        migrations.AlterField(
            model_name='infobuilding',
            name='city',
            field=models.CharField(max_length=200, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='infobuilding',
            name='code_building',
            field=models.IntegerField(default=0, verbose_name='Код дома'),
        ),
        migrations.AlterField(
            model_name='infobuilding',
            name='number_building',
            field=models.CharField(max_length=200, verbose_name='№ дома'),
        ),
        migrations.AlterField(
            model_name='infobuilding',
            name='street',
            field=models.CharField(max_length=200, verbose_name='Название улицы'),
        ),
        migrations.AlterField(
            model_name='regularcustomers',
            name='email_client',
            field=models.EmailField(max_length=255, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='regularcustomers',
            name='name_client',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='regularcustomers',
            name='number_phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='regularcustomers',
            name='surname_client',
            field=models.CharField(max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='statusapartment',
            name='data_change',
            field=models.DateField(blank=True, null=True, verbose_name='Дата изменения статуса'),
        ),
        migrations.AlterField(
            model_name='statusapartment',
            name='id_apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.apartment', verbose_name='ID Апартамента'),
        ),
        migrations.AlterField(
            model_name='statusapartment',
            name='status_apartment',
            field=models.CharField(max_length=200, verbose_name='Статус апартамента'),
        ),
    ]
