# Generated by Django 5.1.2 on 2024-11-08 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0008_alter_applicationwebsite_options_alter_deal_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_deal', models.DateField(blank=True, null=True, verbose_name='Дата сделки')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='realty.apartment', verbose_name='ID Апартамента')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='realty.regularcustomers', verbose_name='ID Клиента')),
            ],
            options={
                'verbose_name': 'Сделка - продано',
                'verbose_name_plural': 'Сделка - продано',
            },
        ),
        migrations.AddField(
            model_name='regularcustomers',
            name='deal2',
            field=models.ManyToManyField(related_name='aparts', through='realty.Deal2', to='realty.apartment'),
        ),
    ]
