# Generated by Django 5.1.2 on 2024-11-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0009_deal2_regularcustomers_deal2'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationwebsite',
            name='date_create',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='applicationwebsite',
            name='status_application',
            field=models.CharField(choices=[('accepted', 'Принято'), ('rejected', 'Отклонено')], max_length=200, verbose_name='Статус заявки'),
        ),
    ]
