# Generated by Django 5.1.2 on 2024-11-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0012_rename_date_create_applicationwebsite_date_create2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationwebsite',
            name='date_create3',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
