# Generated by Django 5.1.2 on 2024-11-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0015_remove_applicationwebsite_date_create2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='apartment_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код апартамента'),
        ),
    ]
