# Generated by Django 5.1.2 on 2024-11-28 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0017_alter_apartment_apartment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusapartment',
            name='id_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.regularcustomers', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='applicationwebsite',
            name='date_create3',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания заявки'),
        ),
        migrations.AlterField(
            model_name='deal2',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='realty.apartment', verbose_name='Код Апартамента'),
        ),
        migrations.AlterField(
            model_name='statusapartment',
            name='id_apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.apartment', verbose_name='Код Апартамента'),
        ),
    ]
