# Generated by Django 5.1.2 on 2024-11-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0018_statusapartment_id_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusapartment',
            name='status_apartment',
            field=models.CharField(choices=[('sold', 'Продано'), ('booked', 'Забронировано'), ('consideration', 'На рассмотрении')], max_length=200, verbose_name='Статус апартамента'),
        ),
    ]
