# Generated by Django 5.1.2 on 2024-12-03 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0019_alter_statusapartment_status_apartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/apartment/', verbose_name='Фото апартамента')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание фото')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='realty.apartment')),
            ],
            options={
                'verbose_name': 'Фото апартамента',
                'verbose_name_plural': 'Фото апартаментов',
            },
        ),
    ]
