# Generated by Django 5.1.2 on 2024-12-27 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("realty", "0021_historicalapartment_historicalapartmentphoto_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Deal",
        ),
    ]
