# Generated by Django 5.1.2 on 2025-01-14 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realty", "0022_delete_deal"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinfobuilding",
            name="updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="infobuilding",
            name="updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
