# Generated by Django 5.1.2 on 2025-01-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realty", "0023_historicalinfobuilding_updated_infobuilding_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinfobuilding",
            name="updated",
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="infobuilding",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
