# Generated by Django 5.1.2 on 2025-01-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realty", "0025_alter_apartment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinfobuilding",
            name="file_document",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Документ"
            ),
        ),
        migrations.AddField(
            model_name="historicalinfobuilding",
            name="website_url",
            field=models.URLField(blank=True, null=True, verbose_name="Сайт"),
        ),
        migrations.AddField(
            model_name="infobuilding",
            name="file_document",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/", verbose_name="Документ"
            ),
        ),
        migrations.AddField(
            model_name="infobuilding",
            name="website_url",
            field=models.URLField(blank=True, null=True, verbose_name="Сайт"),
        ),
    ]
