# Generated by Django 5.1.2 on 2025-01-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realty", "0026_historicalinfobuilding_file_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinfobuilding",
            name="image",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Фото апартамента"
            ),
        ),
        migrations.AddField(
            model_name="infobuilding",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/apartment/",
                verbose_name="Фото апартамента",
            ),
        ),
    ]
