# Generated by Django 5.1.2 on 2025-01-18 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("realty", "0027_historicalinfobuilding_image_infobuilding_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalinfobuilding",
            name="image",
        ),
        migrations.RemoveField(
            model_name="infobuilding",
            name="image",
        ),
    ]
