services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
      - mailhog
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web interface port
  celery:
    build: .
    command: celery -A buildingsite worker -l info
    volumes:
      - ./:/app
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=buildingsite.settings
  celerybeat:
    build: .
    command: celery -A buildingsite beat -l info
    volumes:
      - ./:/app
    depends_on:
      - redis
      - web
    environment:
      - DJANGO_SETTINGS_MODULE=buildingsite.settings
